name: Build LaTeX document

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '.github/workflows/latex-pdf.yml'
  pull_request:
    paths:
      - '**.tex'
      - '**.bib'
      - '.github/workflows/latex-pdf.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create Diagrams for document
      run: |
        conda install python-kaleido
        conda install pandas
        conda install plotly
        cd docs
        mkdir diagrams
        cd ..
        echo generating diagrams...
        pwd
        python docs/gen_diagram.py
    - name: Compile LaTeX (with BibTeX support)
      uses: dante-ev/latex-action@2024-B
      with:
        working_directory: docs
        root_file: Ausarbeitung.tex
        latexmk_use_xelatex: false  # set to true if you use xelatex
        extra-system-packages: collection-science collection-latexrecommended
        extra-font-packages: collection-fontsrecommended
      env:
        BIBINPUTS: 'docs:'
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdf
        path: docs/Ausarbeitung.pdf